
export default new Map([
["src/collections/sections/de/news.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fsections%2Fde%2Fnews.mdx&astroContentModuleFlag=true")],
["src/collections/sections/en/news.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fsections%2Fen%2Fnews.mdx&astroContentModuleFlag=true")],
["src/collections/sections/fr/news.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fsections%2Ffr%2Fnews.mdx&astroContentModuleFlag=true")],
["src/collections/news/de/001-fischermaetteli-fachbericht.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fnews%2Fde%2F001-fischermaetteli-fachbericht.mdx&astroContentModuleFlag=true")],
["src/collections/news/en/001-fischermaetteli-fachbericht.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fnews%2Fen%2F001-fischermaetteli-fachbericht.mdx&astroContentModuleFlag=true")],
["src/collections/news/fr/001-fischermaetteli-fachbericht.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fnews%2Ffr%2F001-fischermaetteli-fachbericht.mdx&astroContentModuleFlag=true")],
["src/collections/news/de/news-1.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fnews%2Fde%2Fnews-1.mdx&astroContentModuleFlag=true")],
["src/collections/news/de/002-astra-zahlenspiele.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fnews%2Fde%2F002-astra-zahlenspiele.mdx&astroContentModuleFlag=true")],
["src/collections/news/en/news-1.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fnews%2Fen%2Fnews-1.mdx&astroContentModuleFlag=true")],
["src/collections/news/fr/news-1.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2Fnews%2Ffr%2Fnews-1.mdx&astroContentModuleFlag=true")],
["src/collections/bigBits/fr/introText01.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2FbigBits%2Ffr%2FintroText01.mdx&astroContentModuleFlag=true")],
["src/collections/bigBits/en/introText01.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2FbigBits%2Fen%2FintroText01.mdx&astroContentModuleFlag=true")],
["src/collections/bigBits/de/introText01.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcollections%2FbigBits%2Fde%2FintroText01.mdx&astroContentModuleFlag=true")]]);
		